### ISSUE TITLE
train codes?

### ISSUE THREAD

**Issue by aa12356jm** [becauseofAI/MobileFace#10]
hi, thanks for your work ,are you plan to  share  the train codes?

**Comment by jackchinor** [comment]
@becauseofAI ,can you share some training tricks on mobileface_identification_V2? I try to train V2 network, howerver the result is not satisfying. the LFW accuracy can only reach to 98%~, which is far less than 99.653%. Could you please give me some hints, really appreciate.

**Comment by becauseofAI** [comment]
@aa12356jm 
At present, the training codes of each module are still messy and can not be unified. When the code is ready in the future, it can be open source.

**Comment by becauseofAI** [comment]
@jackchinor 
Sorry, there was a bug before. I've fixed it. You can try it again.

**Comment by jackchinor** [comment]
@becauseofAI  thanks,I will try it later.
