### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by MyraBaba** [becauseofAI/MobileFace#2]
Hi, 

I have below error:

`  File "/Users/xxx/Projects/MobileFace/example/get_face_feature_mxnet.py", line 25, in __init__
    network = get_feature_symbol_mobilefacev1()
NameError: name 'get_feature_symbol_mobilefacev1' is not defined`

sys.path.append didnt work I assume...

how I can solve ?

**Comment by MyraBaba** [comment]
I found the mistake, in the source you wrote get_feature_symbol_mobilefacev1 . but in the clas : 

get_feature_symbol_mobileface_v1

**Comment by becauseofAI** [comment]
Hi @MyraBaba ,

Sorry for the trouble. I have fixed the error. Thank you for your correction.
