### ISSUE TITLE
mxnet2caffe2？

### ISSUE THREAD

**Issue by aa12356jm** [becauseofAI/MobileFace#6]
look forward to this part  mxnet2caffe, 
（1） is it mxnet2caffe2?      mxnet--->onnx--->caffe2？
（2）is there a android demo?
（3）cpu performance  of readme  refers to  a phone?
thanks for your work.

**Comment by becauseofAI** [comment]
@aa12356jm

**Comment by becauseofAI** [comment]
@aa12356jm 
(1) mxnet2caffe is in plan (not mxnet2caffe2 or mxnet->onnx->caffe2). But you can try.

**Comment by becauseofAI** [comment]
@aa12356jm 
(1) mxnet2caffe is in plan (not mxnet2caffe2 or mxnet->onnx->caffe2). But you can try.
(2) This repo. is mainly to provide basic algorithms now. Android demo maybe to provide in the future if my time is free.
(3) CPU performance in readme is intel cpu.

**Comment by aa12356jm** [comment]
@becauseofAI thanks
