### ISSUE TITLE
pytorch or tensorflow implementation?

### ISSUE THREAD

**Issue by lucasjinreal** [becauseofAI/MobileFace#7]
pytorch or tensorflow implementation?

**Comment by becauseofAI** [comment]
it mainly implemented based on MXNet and Gluon. The model can be ported to other's frameworks such as pytorch, tensorflow and caffe theoretically.

**Comment by becauseofAI** [comment]
It mainly implemented based on MXNet and Gluon. The model can be ported to other's frameworks such as pytorch, tensorflow and caffe theoretically.
